"""create borrowers and financial_snapshots

Revision ID: 52bbd4db7c9f
Revises: 
Create Date: 2026-08-12 22:31:58.908132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52bbd4db7c9f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrowers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('borrower_id', sa.String(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('ebitda', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_operating_income', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('current_assets', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('current_liabilities', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_debt', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('debt_service', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrowers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_snapshots_borrower_id'), 'financial_snapshots', ['borrower_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_snapshots_borrower_id'), table_name='financial_snapshots')
    op.drop_table('financial_snapshots')
    op.drop_table('borrowers')
    # ### end Alembic commands ###
